// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// likseq
double likseq(IntegerVector SNPs, IntegerVector SNPfreqs, IntegerVector nodeparents, NumericVector nodetimes, double mutrate, int obs);
RcppExport SEXP phybreak_likseq(SEXP SNPsSEXP, SEXP SNPfreqsSEXP, SEXP nodeparentsSEXP, SEXP nodetimesSEXP, SEXP mutrateSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type SNPs(SNPsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type SNPfreqs(SNPfreqsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodeparents(nodeparentsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodetimes(nodetimesSEXP);
    Rcpp::traits::input_parameter< double >::type mutrate(mutrateSEXP);
    Rcpp::traits::input_parameter< int >::type obs(obsSEXP);
    __result = Rcpp::wrap(likseq(SNPs, SNPfreqs, nodeparents, nodetimes, mutrate, obs));
    return __result;
END_RCPP
}
// likseqenv
double likseqenv(Environment pbenv, IntegerVector nodestochange, IntegerVector tips);
RcppExport SEXP phybreak_likseqenv(SEXP pbenvSEXP, SEXP nodestochangeSEXP, SEXP tipsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type pbenv(pbenvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodestochange(nodestochangeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tips(tipsSEXP);
    __result = Rcpp::wrap(likseqenv(pbenv, nodestochange, tips));
    return __result;
END_RCPP
}
// CCphylotree
std::vector<double> CCphylotree(const std::vector<int>& pars, const std::vector<double>& tims, std::vector<int> dims);
RcppExport SEXP phybreak_CCphylotree(SEXP parsSEXP, SEXP timsSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type tims(timsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims(dimsSEXP);
    __result = Rcpp::wrap(CCphylotree(pars, tims, dims));
    return __result;
END_RCPP
}
// CCtranstree
std::vector<double> CCtranstree(const std::vector<int>& pars, const std::vector<double>& tims, std::vector<int> dims);
RcppExport SEXP phybreak_CCtranstree(SEXP parsSEXP, SEXP timsSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type tims(timsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dims(dimsSEXP);
    __result = Rcpp::wrap(CCtranstree(pars, tims, dims));
    return __result;
END_RCPP
}
// ptr
std::vector<int> ptr(IntegerVector pars, int ID);
RcppExport SEXP phybreak_ptr(SEXP parsSEXP, SEXP IDSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type ID(IDSEXP);
    __result = Rcpp::wrap(ptr(pars, ID));
    return __result;
END_RCPP
}
// sctwh3
NumericVector sctwh3(NumericVector tle);
RcppExport SEXP phybreak_sctwh3(SEXP tleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tle(tleSEXP);
    __result = Rcpp::wrap(sctwh3(tle));
    return __result;
END_RCPP
}
