# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.CCphylotreeconstruct <- function(pars, dims) {
    .Call('phybreakCO_CCphyloconstruct', PACKAGE = 'phybreakCO', pars, dims)
}

.CCphylotree <- function(pars, dims) {
    .Call('phybreakCO_CCphylotree', PACKAGE = 'phybreakCO', pars, dims)
}

.CCtranstreeconstruct <- function(pars, dims) {
    .Call('phybreakCO_CCtranstreeconstruct', PACKAGE = 'phybreakCO', pars, dims)
}

.CCtranstree <- function(pars, dims) {
    .Call('phybreakCO_CCtranstree', PACKAGE = 'phybreakCO', pars, dims)
}

.likseq <- function(SNPs, SNPfreqs, nodeparents, nodetimes, mutrate, obs) {
    .Call('phybreakCO_likseq', PACKAGE = 'phybreakCO', SNPs, SNPfreqs, nodeparents, nodetimes, mutrate, obs)
}

.likseqenv <- function(pbenv, nodestochange, tips) {
    .Call('phybreakCO_likseqenv', PACKAGE = 'phybreakCO', pbenv, nodestochange, tips)
}

.MLphylotree_MCC <- function(pars, dims) {
    .Call('phybreakCO_MLphylotree_MCC', PACKAGE = 'phybreakCO', pars, dims)
}

.ptr <- function(pars, ID) {
    .Call('phybreakCO_ptr', PACKAGE = 'phybreakCO', pars, ID)
}

.sct <- function(tle) {
    .Call('phybreakCO_sct', PACKAGE = 'phybreakCO', tle)
}

