# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.CCtranstree2 <- function(pars, tims, dims) {
    .Call('_phybreak_CCtranstree2', PACKAGE = 'phybreak', pars, tims, dims)
}

obsarrayC <- function(SNPs, Nsamples) {
    .Call('_phybreak_obsarrayC', PACKAGE = 'phybreak', SNPs, Nsamples)
}

obshostarrayC <- function(obssamplearray, samplehosts, Nhosts) {
    .Call('_phybreak_obshostarrayC', PACKAGE = 'phybreak', obssamplearray, samplehosts, Nhosts)
}

facultyC <- function(x) {
    .Call('_phybreak_facultyC', PACKAGE = 'phybreak', x)
}

chooseC <- function(a, b) {
    .Call('_phybreak_chooseC', PACKAGE = 'phybreak', a, b)
}

transitmatrixC <- function(mutrate, bnsize) {
    .Call('_phybreak_transitmatrixC', PACKAGE = 'phybreak', mutrate, bnsize)
}

likgeneticC <- function(SNPs, SNPfreqs, infectors, samplehosts, mutrate, bnsize) {
    .Call('_phybreak_likgeneticC', PACKAGE = 'phybreak', SNPs, SNPfreqs, infectors, samplehosts, mutrate, bnsize)
}

likgeneticCenv <- function(pbenv, newpar) {
    .Call('_phybreak_likgeneticCenv', PACKAGE = 'phybreak', pbenv, newpar)
}

.likseq <- function(SNPs, SNPfreqs, nodeparents, nodetimes, mutrate, Nsamples) {
    .Call('_phybreak_likseq', PACKAGE = 'phybreak', SNPs, SNPfreqs, nodeparents, nodetimes, mutrate, Nsamples)
}

.likseqenv <- function(pbenv, nodestochange, tips) {
    .Call('_phybreak_likseqenv', PACKAGE = 'phybreak', pbenv, nodestochange, tips)
}

.mcctree <- function(pars, tims, dims) {
    .Call('_phybreak_CCphylotree', PACKAGE = 'phybreak', pars, tims, dims)
}

.mtcctree <- function(pars, tims, dims) {
    .Call('_phybreak_CCtranstree', PACKAGE = 'phybreak', pars, tims, dims)
}

.ptr <- function(pars, ID) {
    .Call('_phybreak_ptr', PACKAGE = 'phybreak', pars, ID)
}

.sctwh3 <- function(tle) {
    .Call('_phybreak_sctwh3', PACKAGE = 'phybreak', tle)
}

